Multi tenancy
Jonathan-Eng/boot-bootcamp pull request #3
Opened 2020-01-16 14:48 UTC by Jonathan-Eng

2020-01-20 16:22 UTC, naorgu requested changes
Kivid of a work

2020-01-20 16:22 UTC, naorgu commented on accounts-service/client/src/main/java/pojos/Account.java
> +    private String esindex;
```suggestion
    private String esIndex;
```

2020-01-20 16:22 UTC, naorgu commented on accounts-service/src/main/java/config/AccountsServiceConfiguration.java
> +public class AccountsServiceConfiguration {
Looks like it is unused

2020-01-20 16:22 UTC, naorgu commented on accounts-service/src/main/java/juice/modules/AccountsServiceModule.java
> +    /*
remove

2020-01-20 16:22 UTC, naorgu commented on accounts-service/src/main/java/jettyjersey/CreateAccountBody.java
> +public class CreateAccountBody {
```suggestion
public class CreateAccountRequest {
```

2020-01-20 16:22 UTC, naorgu commented on accounts-service/client/src/main/java/api/AccountsServiceApi.java
> +            String jsonRequestStr = String.format("{\"accountName\": \"%s\"}", accountName);
You can do instead `new CreateAccountRequest(accountName)`

2020-01-20 16:22 UTC, naorgu commented on indexer/src/main/java/consumer/IndexerConsumer.java
>      public void setTopic(String topic) {
Setter is no beseder

2020-01-20 16:22 UTC, naorgu commented on indexer/src/main/java/consumer/IndexerConsumer.java
> +        this.accountsServiceApi = new AccountsServiceApi();
This should be injected using Guice, right?

2020-01-20 16:22 UTC, naorgu commented on logs-shipper/src/main/java/jettyjersey/SearchResource.java
> +        this.accountsServiceApi = new AccountsServiceApi();
should be injected

2020-01-20 16:22 UTC, naorgu commented on logs-shipper/src/main/java/jettyjersey/IndexResource.java
> +        this.accountsServiceApi = new AccountsServiceApi();
Should be injected

2020-01-20 16:22 UTC, naorgu commented on logs-shipper/src/main/java/jettyjersey/IndexResource.java
>      private String topic = "my_topic";
The topic should be part of the configuration

2020-01-20 16:22 UTC, naorgu commented on indexer/src/main/java/consumer/IndexerConsumer.java
>      private String topic = "my_topic";
should be configurable

2020-01-20 16:22 UTC, naorgu commented on indexer/src/main/java/consumer/IndexerConsumer.java
> +                Map<String, String> rValAsMap = JsonParser.getObjFromJsonString(r.value(), Map.class);
Should be `Map<String, Object>`

2020-01-20 16:22 UTC, naorgu commented on inf/src/main/java/parser/JsonParser.java
> +    public static <T> String getJsonStringFromObject(T obj) {
Notice here the generic `<T>` has no use - could just accept `Object` instead

2020-01-20 16:22 UTC, naorgu commented on logs-shipper/src/main/java/jettyjersey/IndexResource.java
>      public String getTopic() {
Remove this and `setTopic`

2020-01-20 16:22 UTC, naorgu commented on indexer/src/main/java/consumer/IndexerConsumer.java
> +                e.printStackTrace();
Looks like you swallow an exception here - I guess you want to return to the client some kind of error response

2020-01-20 16:22 UTC, naorgu commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
>      private final ServerConfiguration sc;
This is unused. delete

2020-01-20 16:22 UTC, naorgu commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
>                  ServerConfiguration.class);
remove

2020-01-20 16:22 UTC, naorgu commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
> +    private LogsShipperClient handler;
```suggestion
    private LogsShipperClient logsShipperClient;
```

2020-01-20 16:22 UTC, naorgu commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
> +    private static int genRandAccountNum() {
```suggestion
    private static int genRandAccountName() {
```

2020-01-20 16:22 UTC, naorgu commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
>  }
Let's add tests for unauthorized token when searching/indexing

2020-01-20 16:22 UTC, naorgu commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
> +        return "{\"message\":\"" + msg + "\"}";
Let's use instead `JsonParser.getJsonStringFromObject(new IndexBody(msg))`

2020-01-20 16:22 UTC, naorgu commented on accounts-service/client/src/main/java/api/AccountsServiceApi.java
> +}
Very nice implementation

2020-01-20 16:53 UTC, Jonathan-Eng commented on accounts-service/src/main/java/config/AccountsServiceConfiguration.java
> +public class AccountsServiceConfiguration {
removed

2020-01-20 16:53 UTC, Jonathan-Eng commented on accounts-service/src/main/java/juice/modules/AccountsServiceModule.java
> +    /*
done

2020-01-20 16:56 UTC, Jonathan-Eng commented on accounts-service/src/main/java/jettyjersey/CreateAccountBody.java
> +public class CreateAccountBody {
done

2020-01-21 08:35 UTC, Jonathan-Eng commented on accounts-service/client/src/main/java/api/AccountsServiceApi.java
> +            String jsonRequestStr = String.format("{\"accountName\": \"%s\"}", accountName);
done

2020-01-21 08:35 UTC, Jonathan-Eng commented on indexer/src/main/java/consumer/IndexerConsumer.java
>      public void setTopic(String topic) {
this is because you told me we should make the topic configurable.

2020-01-21 16:33 UTC, Jonathan-Eng commented on indexer/src/main/java/consumer/IndexerConsumer.java
>      public void setTopic(String topic) {
i will make it configurable with a file

2020-01-21 16:33 UTC, Jonathan-Eng commented on indexer/src/main/java/consumer/IndexerConsumer.java
> +        this.accountsServiceApi = new AccountsServiceApi();
yes. done

2020-01-21 17:20 UTC, Jonathan-Eng commented on logs-shipper/src/main/java/jettyjersey/SearchResource.java
> +        this.accountsServiceApi = new AccountsServiceApi();
done

2020-01-21 17:23 UTC, Jonathan-Eng commented on logs-shipper/src/main/java/jettyjersey/IndexResource.java
> +        this.accountsServiceApi = new AccountsServiceApi();
done

2020-01-21 18:21 UTC, Jonathan-Eng commented on indexer/src/main/java/consumer/IndexerConsumer.java
> +                Map<String, String> rValAsMap = JsonParser.getObjFromJsonString(r.value(), Map.class);
done

2020-01-26 07:38 UTC, Jonathan-Eng commented on inf/src/main/java/parser/JsonParser.java
> +    public static <T> String getJsonStringFromObject(T obj) {
done

2020-01-26 09:15 UTC, Jonathan-Eng commented on indexer/src/main/java/consumer/IndexerConsumer.java
> +                e.printStackTrace();
which kind of error response? throwing exceptions invoked in the foreach loop is apparently forbidden.

2020-01-26 11:29 UTC, Jonathan-Eng commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
>      private final ServerConfiguration sc;
used here :
`private static int genRandAccountNum() {
        return new Random().nextInt(ACCOUNT_RAND_HIGH - ACCOUNT_RAND_LOW) + ACCOUNT_RAND_LOW;
    }`

2020-01-26 12:01 UTC, Jonathan-Eng commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
> +    private LogsShipperClient handler;
done

2020-01-26 12:09 UTC, Jonathan-Eng commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
> +    private static int genRandAccountNum() {
done

2020-01-26 12:16 UTC, Jonathan-Eng commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
> +        return "{\"message\":\"" + msg + "\"}";
done

2020-01-26 21:10 UTC, Jonathan-Eng commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
>  }
done

2020-01-26 21:13 UTC, Jonathan-Eng commented on logs-shipper/src/test/java/jettyjersey/ResourceTest.java
>                  ServerConfiguration.class);
done

2020-01-26 21:31 UTC, Jonathan-Eng commented on accounts-service/client/src/main/java/pojos/Account.java
> +    private String esindex;
done

2020-01-27 13:02 UTC, Jonathan-Eng commented on indexer/src/main/java/consumer/IndexerConsumer.java
>      public void setTopic(String topic) {
done

2020-01-27 13:03 UTC, Jonathan-Eng commented on logs-shipper/src/main/java/jettyjersey/IndexResource.java
>      private String topic = "my_topic";
done

2020-01-27 13:03 UTC, Jonathan-Eng commented on indexer/src/main/java/consumer/IndexerConsumer.java
>      private String topic = "my_topic";
done

2020-01-27 13:04 UTC, Jonathan-Eng commented on logs-shipper/src/main/java/jettyjersey/IndexResource.java
>      public String getTopic() {
done

2020-01-28 10:49 UTC, merged